// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: dispatcher/v1/dispatch.proto

package dispatcher

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_dispatcher_v1_dispatch_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "dispatcher.v1.generate_dispatcher",
		Tag:           "bytes,50001,opt,name=generate_dispatcher",
		Filename:      "dispatcher/v1/dispatch.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional string generate_dispatcher = 50001;
	E_GenerateDispatcher = &file_dispatcher_v1_dispatch_proto_extTypes[0]
)

var File_dispatcher_v1_dispatch_proto protoreflect.FileDescriptor

const file_dispatcher_v1_dispatch_proto_rawDesc = "" +
	"\n" +
	"\x1cdispatcher/v1/dispatch.proto\x12\rdispatcher.v1\x1a google/protobuf/descriptor.proto:Q\n" +
	"\x13generate_dispatcher\x12\x1e.google.protobuf.MethodOptions\x18ц\x03 \x01(\tR\x12generateDispatcherB\xc9\x01\n" +
	"\x11com.dispatcher.v1B\rDispatchProtoP\x01ZPgithub.com/wargasipil/protoc-gen-dispatcher/example_gen/dispatcher/v1;dispatcher\xa2\x02\x03DXX\xaa\x02\rDispatcher.V1\xca\x02\rDispatcher\\V1\xe2\x02\x19Dispatcher\\V1\\GPBMetadata\xea\x02\x0eDispatcher::V1b\x06proto3"

var file_dispatcher_v1_dispatch_proto_goTypes = []any{
	(*descriptorpb.MethodOptions)(nil), // 0: google.protobuf.MethodOptions
}
var file_dispatcher_v1_dispatch_proto_depIdxs = []int32{
	0, // 0: dispatcher.v1.generate_dispatcher:extendee -> google.protobuf.MethodOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dispatcher_v1_dispatch_proto_init() }
func file_dispatcher_v1_dispatch_proto_init() {
	if File_dispatcher_v1_dispatch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dispatcher_v1_dispatch_proto_rawDesc), len(file_dispatcher_v1_dispatch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_dispatcher_v1_dispatch_proto_goTypes,
		DependencyIndexes: file_dispatcher_v1_dispatch_proto_depIdxs,
		ExtensionInfos:    file_dispatcher_v1_dispatch_proto_extTypes,
	}.Build()
	File_dispatcher_v1_dispatch_proto = out.File
	file_dispatcher_v1_dispatch_proto_goTypes = nil
	file_dispatcher_v1_dispatch_proto_depIdxs = nil
}
