// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: example/v1/example.proto

package exampleconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/wargasipil/protoc-gen-dispatcher/example_gen/example/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HelloServiceName is the fully-qualified name of the HelloService service.
	HelloServiceName = "example.v1.HelloService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HelloServiceHelloProcedure is the fully-qualified name of the HelloService's Hello RPC.
	HelloServiceHelloProcedure = "/example.v1.HelloService/Hello"
	// HelloServiceHelloClientProcedure is the fully-qualified name of the HelloService's HelloClient
	// RPC.
	HelloServiceHelloClientProcedure = "/example.v1.HelloService/HelloClient"
)

// HelloServiceClient is a client for the example.v1.HelloService service.
type HelloServiceClient interface {
	Hello(context.Context, *connect.Request[v1.HelloRequest]) (*connect.Response[v1.HelloResponse], error)
	HelloClient(context.Context) *connect.BidiStreamForClient[v1.HelloClientRequest, v1.HelloClientResponse]
}

// NewHelloServiceClient constructs a client for the example.v1.HelloService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHelloServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HelloServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	helloServiceMethods := v1.File_example_v1_example_proto.Services().ByName("HelloService").Methods()
	return &helloServiceClient{
		hello: connect.NewClient[v1.HelloRequest, v1.HelloResponse](
			httpClient,
			baseURL+HelloServiceHelloProcedure,
			connect.WithSchema(helloServiceMethods.ByName("Hello")),
			connect.WithClientOptions(opts...),
		),
		helloClient: connect.NewClient[v1.HelloClientRequest, v1.HelloClientResponse](
			httpClient,
			baseURL+HelloServiceHelloClientProcedure,
			connect.WithSchema(helloServiceMethods.ByName("HelloClient")),
			connect.WithClientOptions(opts...),
		),
	}
}

// helloServiceClient implements HelloServiceClient.
type helloServiceClient struct {
	hello       *connect.Client[v1.HelloRequest, v1.HelloResponse]
	helloClient *connect.Client[v1.HelloClientRequest, v1.HelloClientResponse]
}

// Hello calls example.v1.HelloService.Hello.
func (c *helloServiceClient) Hello(ctx context.Context, req *connect.Request[v1.HelloRequest]) (*connect.Response[v1.HelloResponse], error) {
	return c.hello.CallUnary(ctx, req)
}

// HelloClient calls example.v1.HelloService.HelloClient.
func (c *helloServiceClient) HelloClient(ctx context.Context) *connect.BidiStreamForClient[v1.HelloClientRequest, v1.HelloClientResponse] {
	return c.helloClient.CallBidiStream(ctx)
}

// HelloServiceHandler is an implementation of the example.v1.HelloService service.
type HelloServiceHandler interface {
	Hello(context.Context, *connect.Request[v1.HelloRequest]) (*connect.Response[v1.HelloResponse], error)
	HelloClient(context.Context, *connect.BidiStream[v1.HelloClientRequest, v1.HelloClientResponse]) error
}

// NewHelloServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHelloServiceHandler(svc HelloServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	helloServiceMethods := v1.File_example_v1_example_proto.Services().ByName("HelloService").Methods()
	helloServiceHelloHandler := connect.NewUnaryHandler(
		HelloServiceHelloProcedure,
		svc.Hello,
		connect.WithSchema(helloServiceMethods.ByName("Hello")),
		connect.WithHandlerOptions(opts...),
	)
	helloServiceHelloClientHandler := connect.NewBidiStreamHandler(
		HelloServiceHelloClientProcedure,
		svc.HelloClient,
		connect.WithSchema(helloServiceMethods.ByName("HelloClient")),
		connect.WithHandlerOptions(opts...),
	)
	return "/example.v1.HelloService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HelloServiceHelloProcedure:
			helloServiceHelloHandler.ServeHTTP(w, r)
		case HelloServiceHelloClientProcedure:
			helloServiceHelloClientHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHelloServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHelloServiceHandler struct{}

func (UnimplementedHelloServiceHandler) Hello(context.Context, *connect.Request[v1.HelloRequest]) (*connect.Response[v1.HelloResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("example.v1.HelloService.Hello is not implemented"))
}

func (UnimplementedHelloServiceHandler) HelloClient(context.Context, *connect.BidiStream[v1.HelloClientRequest, v1.HelloClientResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("example.v1.HelloService.HelloClient is not implemented"))
}
